-- ADD[옵션: 추가] ADD GENDER VARCHAR(9)[새로운 컬럼]
-- ADD[옵션: 수정] MODIFY (특정한 정보만 추가 X 컬럼의 정보를 다시 씀 (형이나 NOT NULL 여부 같은 것도 매번 써줘야 함)

-- 회원 테이블에 성별 컬럼 추가
ALTER TABLE CUSTOMER ADD GENDER VARCHAR(9);

-- 성별 컬럼의 크기 변경
ALTER TABLE CUSTOMER MODIFY GENDER VARCHAR(100);

-- 성별 컬럼 자료형과 NOT NULL 변경
ALTER TABLE CUSTOMER MODIFY GENDER INT NOT NULL; -- INT, NOT NULL

-- 성별 컬럼에 설명 추가
ALTER TABLE CUSTOMER MODIFY GENDER INT NOT NULL COMMENT '성별';

-- 컬럼의 이름은 MODIFY로 변경 불가

-- 성별 컬럼의 이름 변경

-- 이름만 변경할 때 사용
ALTER TABLE CUSTOMER RENAME COLUMN GENDER TO GEN;

-- 이름과 다른 옵션을 한 번에 변경할 때 사용
ALTER TABLE CUSTOMER CHANGE COLUMN GEN GENDER VARCHAR(9);

-- 이름, 주소, 성별 컬럼 삭제
ALTER TABLE CUSTOMER DROP COLUMN NAME;
ALTER TABLE CUSTOMER DROP COLUMN ADDRESS;
ALTER TABLE CUSTOMER DROP COLUMN GENDER;
-- ID까지는 삭제 불가능, 데이터에 컬럼이 하나도 없을 순 없음

-- PRIMARY KEY는 컬럼이 아니라 컬럼에 종속된 데이터
-- 컬럼 데이터 변경으로는 바뀌지 않음

-- 문제 1. CUSTOMER 회원 테이블에 다시 컬럼 3개 추가

ALTER TABLE CUSTOMER ADD NAME VARCHAR(20) NOT NULL;
ALTER TABLE CUSTOMER ADD ADDRESS VARCHAR(100);
ALTER TABLE CUSTOMER ADD GENGER VARCHAR(9);

-- 문제 2. ORDERS 주문 테이블을 다음과 같이 변경
-- 1) 판매자 아이디 컬럼의 이름을 SALESMAN_NAME으로 변경
-- 2) 주문일자 컬럼 삭제

ALTER TABLE ORDERS RENAME COLUMN SALESMAN_ID TO SALESMAN_NAME;
ALTER TABLE ORDERS DROP COLUMN ORDER_DATE;

-- 문제 3. LOCATION 위치 테이블을 다음과 같이 변경
-- 모든 컬럼에 코멘트 작성

ALTER TABLE LOCATION MODIFY LOCATION_ID INT COMMENT '위치 번호';
ALTER TABLE LOCATION MODIFY ADDRESS VARCHAR(255) NOT NULL COMMENT '주소';
ALTER TABLE LOCATION MODIFY POSTAL_CODE VARCHAR(20) COMMENT '우편 번호';
ALTER TABLE LOCATION MODIFY CITY VARCHAR(50) COMMENT '도시명';

-- 문제 4. CURRICULUM 수업 테이블을 다음과 같이 변경
-- 모든 컬럼의 이름과 NOT NULL 여부 변경

ALTER TABLE CURRICULUM RENAME COLUMN NO TO CURRICULUM_NO;
ALTER TABLE CURRICULUM CHANGE COLUMN NAME CURRICULUM_NAME VARCHAR(30) NOT NULL COMMENT '과목명';
ALTER TABLE CURRICULUM CHANGE COLUMN POINTS CURRICULUM_POINTS INT NOT NULL COMMENT '학점';
ALTER TABLE CURRICULUM CHANGE COLUMN PROFID CURRICULUM_PROFID INT NOT NULL COMMENT '교수 번호';

-- 문제 5. EMP 직원 테이블을 다음과 같이 변경
-- 월급 컬럼 추가
-- 모든 컬럼에 코멘트 작성

ALTER TABLE EMP ADD SALARY INT NOT NULL COMMENT '월급';
ALTER TABLE EMP MODIFY EMP_NO INT COMMENT '직원 번호';
ALTER TABLE EMP MODIFY DEPT_NO INT COMMENT '부서 번호';
ALTER TABLE EMP MODIFY EMP_NAME VARCHAR(10) COMMENT '직원 이름';
ALTER TABLE EMP MODIFY HDATE DATE COMMENT '입사일';