-- CUSTOMER 테이블 삭제
DROP TABLE CUSTOMER;

-- 문제 1. 데이터베이스에 있는 모든 테이블 삭제

DROP TABLE CATEGORIES;
DROP TABLE CINEMA;
DROP TABLE CURRICULUM;
DROP TABLE DEPT;
DROP TABLE EMP;
DROP TABLE LOCATION;
DROP TABLE MENUS;
DROP TABLE ORDERS;
DROP TABLE RESERVATION;